var extended = [null, 0x5c, 0x5d, 0x5e, 0x60, 0x61, 0x62, 0x63, 0x7e, 0xaa, 0xbb, 0xef];

var tokens = [
    "", "►DMS", "►Dec", "►Frac", "→", "Boxplot", "[", "]", "{", "}", "ʳ", "°", "⁻¹", "²", "ᵀ", "³", 
    "(", ")", "round(", "pxl-Test(", "augment(", "rowSwap(", "row+(", "*row(", "*row+(", "max(", "min(", "R►Pr(", "R►Pθ(", "P►Rx(", "P►Ry(", "median(", 
    "randM(", "mean(", "solve(", "seq(", "fnInt(", "nDeriv(",, "fMin(", "fMax(", " ", "\"", ",", "𝑖", "!", "CubicReg ", "QuartReg ", 
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ".", "ᴇ", " or ", " xor ", ":", "\n", 
    " and ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", 
    "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "θ",,,, "Prgm",
    ,,,,"Radian", "Degree", "Normal", "Sci", "Eng", "Float", "=", "<", ">", "≤", "≥", "≠",
    "+", "-", "Ans", "Fix ", "Horiz", "Full", "Func", "Param", "Polar", "Seq", "IndpntAuto", "IndpntAsk", "DependAuto", "DependAsk",, "□",
    "﹢", "·", "*", "/", "Trace", "ClrDraw", "ZStandard", "ZTrig", "ZBox", "Zoom In", "Zoom Out", "ZSquare", "ZInteger", "ZPrevious", "ZDecimal", "ZoomStat",
    "ZoomRcl", "PrintScreen", "ZoomSto", "Text(", " nPr ", " nCr ", "FnOn ", "FnOff ", "StorePic ", "RecallPic ", "StoreGDB ", "RecallGDB ", "Line(", "Vertical ", "Pt-On(", "Pt-Off(",
    "Pt-Change(", "Pxl-On(", "Pxl-Off(", "Pxl-Change(", "Shade(", "Circle(", "Horizontal ", "Tangent(", "DrawInv ", "DrawF ",, "rand", "π", "getKey", "\'", "?",
    "⁻", "int(", "abs(", "det(", "identity(", "dim(", "sum(", "prod(", "not(", "iPart(", "fPart(",, "√(", "³√(", "ln(", "𝑒^(",
    "log(", "₁₀^(", "sin(", "sin⁻¹(", "cos(", "cos⁻¹(", "tan(", "tan⁻¹(", "sinh(", "sinh⁻¹(", "cosh(", "cosh⁻¹(", "tanh(", "tanh⁻¹(", "If ", "Then",
    "Else", "While ", "Repeat ", "For(", "End", "Return", "Lbl ", "Goto ", "Pause ", "Stop", "IS>(", "DS<(", "Input ", "Prompt ", "Disp ", "DispGraph",
    "Output(", "ClrHome", "Fill(", "SortA(", "SortD(", "DispTable", "Menu(", "Send(", "Get(", "PlotsOn ", "PlotsOff ", "ʟ", "Plot1(", "Plot2(", "Plot3(",,
    "^", "ˣ√", "1-Var Stats ", "2-Var Stats ", "LinReg(a+bx) ", "ExpReg ", "LnReg ", "PwrReg ", "Med-Med ", "QuadReg ", "ClrList ", "ClrTable", "Histogram", "xyLine", "Scatter", "LinReg(ax+b) ",

// 0x5C Matrices
    "[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]", "[J]",,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
// 0x5D Lists
    "L₁", "L₂", "L₃", "L₄", "L₅", "L₆",,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
//0x5E Equations
    ,,,,,,,,,,,,,,,,
    "Y₁", "Y₂", "Y₃", "Y₄", "Y₅", "Y₆", "Y₇", "Y₈", "Y₉", "Y₀",,,,,,,
    "X₁ᴛ", "Y₁ᴛ", "X₂ᴛ", "Y₂ᴛ", "X₃ᴛ", "Y₃ᴛ", "X₄ᴛ", "Y₄ᴛ", "X₅ᴛ", "Y₅ᴛ", "X₆ᴛ", "Y₆ᴛ",,,,
    ,,,,,,,,,,,,,,,,
    "r₁", "r₂", "r₃", "r₄", "r₅", "r₆",,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    "|u", "|v", "|w",,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,

// 0x60 Pictures
    "Pic1", "Pic2", "Pic3", "Pic4", "Pic5", "Pic6", "Pic7", "Pic8", "Pic9", "Pic0",,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,

// 0x61 GDBs
    "GDB1", "GDB2", "GDB3", "GDB4", "GDB5", "GDB6", "GDB7", "GDB8", "GDB9", "GDB0",,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,

// 0x62 Statistics
    ,"RegEQ", "n", "x̄", "Σx", "Σx²", "[Sx]", "σx", "[minX]", "[maxX]", "[minY]", "[maxY]", "ȳ", "Σy", "Σy²", "[Sy]",
    "σy", "Σxy", "[r]", "[Med]", "Q₁", "Q₃", "[|a]", "[|b]", "[|c]", "[|d]", "[|e]", "x₁", "x₂", "x₃", "y₁", "y₂",
    "y₃", "𝑛", "[p]", "[z]", "[t]", "χ²", "[|F]", "[df]", "p̂", "p̂₁", "p̂₂", "x̄₁", "Sx₁", "n₁", "x̄₂", "Sx₂",
    "n₂", "Sxp", "lower", "upper", "[s]", "r²", "R²", "[factordf]", "[factorSS]", "[factorMS]", "[errordf]", "[errorSS]", "[errorMS]",,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
// 0x63 Window and Finance
    "ZXscl", "ZYscl", "Xscl", "Yscl", "u(𝑛Min)", "v(𝑛Min)", "U𝑛-₁", "V𝑛-₁", "Zu(𝑛Min)", "Zv(𝑛Min)", "Xmin", "Xmax", "Ymin", "Ymax", "Tmin", "Tmax",
    "θMin", "θMax", "ZXmin", "ZXmax", "ZYmin", "ZYmax", "Zθmin", "Zθmax", "ZTmin", "ZTmax", "TblStart", "PlotStart", "ZPlotStart", "𝑛Max", "Z𝑛Max", "𝑛Min",
    "Z𝑛Min", "∆Tbl", "Tstep", "θstep", "ZTstep", "Zθstep", "∆X", "∆Y", "XFact", "YFact", "TblInput", "𝗡", "I%", "PV", "PMT", "FV",
    "|P/Y", "|C/Y", "w(𝑛Min)", "Zw(𝑛Min)", "PlotStep", "ZPlotStep", "Xres", "ZXres", "TraceStep",,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,

// 0x7E Graph Format Menu and Mode Menu
    "Sequential", "Simul", "PolarGC", "RectGC", "CoordOn", "CoordOff", "Thick", "Dot-Thick", "AxesOn ", "AxesOff", "GridDot ", "GridOff", "LabelOn", "LabelOff", "Web", "Time",
    "uvAxes", "vwAxes", "uwAxes",,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
// 0xAA Strings
    "Str1", "Str2", "Str3", "Str4", "Str5", "Str6", "Str7", "Str8", "Str9", "Str0",,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,

// 0xBB Miscellaneous Tokens
    "npv(", "irr(", "bal(", "ΣPrn(", "ΣInt(", "►Nom(", "►Eff(", "dbd(", "lcm(", "gcd(", "randInt(", "randBin(", "sub(", "stdDev(", "variance(", "inString(",
    "normalcdf(", "invNorm(", "tcdf(", "χ²cdf(", "𝐅cdf(", "binompdf(", "binomcdf(", "poissonpdf(", "poissoncdf(", "geometpdf(", "geometcdf(", "normalpdf(", "tpdf(", "χ²pdf(", "𝐅pdf(", "randNorm(",
    "tvm_Pmt", "tvm_I%", "tvm_PV", "tvm_𝗡", "tvm_FV", "conj(", "real(", "imag(", "angle(", "cumSum(", "expr(", "length(", "ΔList(", "ref(", "rref(", "►Rect",
    "►Polar", "𝑒", "SinReg ", "Logistic ", "LinRegTTest ", "ShadeNorm(", "Shade_t(", "Shadeχ²(", "Shade𝐅(", "Matr►list(", "List►matr(", "Z-Test(", "T-Test ", "2-SampZTest(", "1-PropZTest(", "2-PropZTest(",
    "χ²-Test(", "ZInterval ", "2-SampZInt(", "1-PropZInt(", "2-PropZInt(", "GraphStyle(", "2-SampTTest ", "2-Samp𝐅Test ", "TInterval ", "2-SampTInt ", "SetUpEditor ", "Pmt_End", "Pmt_Bgn", "Real", "r𝑒^θ𝑖", "a+b𝑖",
    "ExprOn", "ExprOff", "ClrAllLists", "GetCalc(", "DelVar ", "Equ►String(", "String►Equ(", "Clear Entries", "Select(", "ANOVA(", "ModBoxplot", "NormProbPlot",,,,,
    ,,,,"G-T", "ZoomFit", "DiagnosticOn", "DiagnosticOff", "Archive ", "UnArchive ", "Asm(", "AsmComp(", "AsmPrgm", "[CompiledAsm83P]", "Á", "À",
    "Â", "Ä", "á", "à", "â", "ä", "É", "È", "Ê", "Ë", "é", "è", "ê", "ë",,"Ì",
    "Î", "Ï", "í", "ì", "î", "ï", "Ó", "Ò", "Ô", "Ö", "ó", "ò", "ô", "ö", "Ú", "Ù",
    "Û", "Ü", "ú", "ù", "û", "ü", "Ç", "ç", "Ñ", "ñ", "´", "`", "¨", "¿", "¡", "α",
    "β", "γ", "Δ", "δ", "ε", "λ", "μ", "|π", "ρ", "Σ",, "Φ", "Ω", "ṗ", "χ", "𝐅",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",,"l", "m", "n", "o", 
    "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "σ", "τ", "Í", "GarbageCollect", "~",
    "\'", "@", "#", "$", "&", "‛", ";", "\\", "|", "_", "%", "…", "∠", "ß", "ˣ", "ᴛ",
    "₀", "₁", "₂", "₃", "₄", "₅", "₆", "₇", "₈", "₉", "₁₀", "◄", "►", "↑", "↓",,
    "×", "∫", "🡅", "🡇","√", "⌸",,,,,,,,,,,

// 0xEF TI-84+
    "setDate(", "setTime(", "checkTmr(", "setDtFmt(", "setTmFmt(", "timeCnv(", "dayOfWk(", "getDtStr(", "getTmStr(", "getDate", "getTime", "startTmr", "getDtFmt", "getTmFmt", "isClockOn", "ClockOff",
    "ClockOn", "OpenLib(", "ExecLib ", "invT(", "χ²GOF-Test(", "LinRegTInt ", "Manual-Fit ", "ZQuadrant1", "ZFrac1⁄2", "ZFrac1⁄3", "ZFrac1⁄4", "ZFrac1⁄5", "ZFrac1⁄8", "ZFrac1⁄10", "⬚",,
    ,,,,,,,,,,,,,,"⁄","ᵤ",
    "►n⁄d◄►Un⁄d", "►F◄►D", "remainder(", "Σ(", "logBASE(", "randIntNoRep(", "CLASSIC", "MATHPRINT", "CLASSIC", "n⁄d", "Un⁄d", "AUTO", "DEC", "FRAC-APPROX",, "STATWIZARD ON",
    "STATWIZARD OFF", "BLUE", "RED", "BLACK", "MAGENTA", "GREEN", "ORANGE", "BROWN", "NAVY", "LTBLUE", "YELLOW", "WHITE", "LTGRAY", "MEDGRAY", "GRAY", "DARKGRAY",
    "Image1", "Image2", "Image3", "Image4", "Image5", "Image6", "Image7", "Image8", "Image9", "Image0", "GridLine ", "BackgroundOn ",,,,,
    ,,,,"BackgroundOff", "GraphColor(", "QuickPlot&Fit-EQ", "TextColor(", "Asm84CPrgm", "[CompiledAsm84C]", "DetectAsymOn", "DetectAsymOff", "BorderColor ",,,,
    ,,,"·", "Thin", "Dot-Thin",,,,,"Asm84CEPrgm", "[CompiledAsmCE]",,,,,
    ,"Quartiles Setting…", "u(𝑛-2)", "v(𝑛-2)", "w(𝑛-2)", "u(𝑛-1)", "v(𝑛-1)", "w(𝑛-1)", "u(𝑛)", "v(𝑛)", "w(𝑛)", "u(𝑛+1)", "v(𝑛+1)", "w(𝑛+1)",, "SEQ(𝑛)",
    "SEQ(𝑛+1)", "SEQ(𝑛+2)", "LEFT", "CENTER", "RIGHT", "invBinom(", "Wait ", "toString(", "eval(",,,,,,"Execute Program", "Undo Clear",
    "Insert Line Above", "Cut Line", "Copy Line", "Paste Line Below", "Insert Comment Above", "Quit Editor", "piecewise(",,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,
];

